### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by shimeeuisuk** [shimeeuisuk/Todo-App-Practice#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성, 삭제, 수정 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Todo 생성, 삭제, 수정 기능을 위한 api 사용하기
2. [ ] Todo App styled component 사용하기
3. [ ] 상태관리를 위해 redux 사용하기
4. [ ] 테스트코드 짜보기

### 예상 시간
24h
